server:
  port: 8090
spring:
  profiles:
    active: nanri
  jpa:
    show-sql: true
  security:
    user:
      name: admin
      password: admin


#mybatis-plus 打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
   tracer: trace
  file:
    path: log

