server:
  port: 8090
spring:
  redis:
# 集群配置
#    cluster:
#      nodes: 192.168.20.214:7000
#    password: xxxxx
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 8
#        min-idle: 2
#        max-wait: 10
##############哨兵模式
#    password: xxxx
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.20.214:27001
#        - 192.168.20.214:27003
#        - 192.168.20.214:27002
#      lettuce:
#        pool:
#          max-active: 10
#          max-idle: 8
#          min-idle: 2
#          max-wait: 100
#    timeout: 5000
##############单机
    host: 192.168.20.214
    password: xxxx
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
    port: 6379